import random

def boDia():

    cadenaSaudo = ["Bo día desde o ciberespazo!",
                   "Bo día. Menos bla bla e máis glu glu!",
                   "Bo día. Viva el vino!",
                   "Bo día. O carajillo de onte estaba carjado de carallo...",
                   "Bo día. Cuidadin con la fiesta que te la quitan de los fuciños.",
                   "Bo día. Está complicado baixar a discografía de Ana Kiro...",
                   "Bo día. Mi amigo el narco y yo, viajamos con la esperaaaanza, ver a Nuñeź Feijoó",
                   "Bo día. Na miña escala de valores, o Ribeiro está por riba dos meus principios.",
                   "Teño carrachas na segunda placa de RAM. A ver se pasades por aquí e limpades un pouco.",
                   "Seguide así eh, que vai tocar o cuponaso.",
                   "El conveeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeenioooooor, JAR!",
                   "Ata logo convenio, ola Julín",
                   "O xoves aquí imbra a chupitada, café e bola.",
                   "Bo día. I wannabe an Apeloner.",
                   "Bo día. Insisto, quero ir ó Peña.",
                   "Bo día. Con tanto torrent nado en la ambulancia chaval.",
                   "Juan Domingo, dime algo con amor: amortiguador.",
                   "Ata os 6 anos pensei que o meu nome era baixadeaí.",
                   "Temos que quedar para facer unha comida...e bebida tamén.",
                   "O único que ten de intelixente é o teléfono. Complete la frase: B____A R__D__",
                   "Hoxe estou como a táboa do un: dame todo igual.",
                   "Está todo moi mal...",
                   "Bueno carallo bueno, aquí tedes o resumo diario.", 
                   "Bo día e boa sorte. Mercade cupón a Juchito que hoxe toca. Resumo do día: ", 
                   "Bo día para vos, tiven pesadelos, todo eran ceros e uns, incluso vin un dous...:",
                   "Bo día a tódalas persoas que teñen fe nos convenios:",
                   "Aguambabulubabalambambu, aquí tedes o resumo:",
                   "¿Activar un antivirus?, estou baixando porno en Galego. Aquí tedes o resumo : ",
                   "Un convenio de 2500€ ou 2500 convenios de A EURO? ",
                   "Cerveza e viño: bo camiño. Resumo de hoxe: ",
                   "Discos duros, queren subir o IVE dos discos duros!. Resumo de hoxe: ",
                   "Hay que fabricar máquinas que nos permitan seguir fabricando máquinas, porque lo que no va a hacer nunca la máquina es fabricar máquinas.",
                   "Dije que bajaría los torrents y los estoy subiendo. ",
                   "El Pulpo de Mugardos no es cosa menor, dicho de otra forma, es cosa mayor",
                   "Is very difficult todo esto:",
                   "¿Ustedes piensan antes de descargar o descargan tras pensar?:",
                   "Bo día. Ide pensando en mercar outro disco. ",
                   "Bo día. Como vai o do convenio? ",
                   "Bo día. Teño un picor telita na segunda placa da RAM. ",
                   "Bo día. Aquí apesta a callos, creo que deixaron unha pota no lume toda a noite.",
                   "Bo día. Na televisión da planta baixa so ven TreceTV.",
                   "Bo día. Como esto siga así voume a convertir nunha parrilla para churrasco. Resumo de hoxe : ",
                   "Bo día. 1 kilo de churrasco para un, cheja. Resumo de hoxe: ",
                   "Bo día. Superamos o de LO ESTÁN REVISANDO ou temos xa convenio" ,
                   "Bo día. Teño ganas de bailar un agarrao con la Bego...Agarrado a tu convenio, perreando la noche enteraaaa.",
                   "Bo día. Necesito un convenio para recuperar a relación.",
                   "Bo día. Mola máis borrador do convenio que o Aranjuez de Rodrigo...",
                   "Tanto convenio y tanta ostia...teremos que recurrir ao Chupa Chups...",
                   "Bo día. Onte pola tarde vin licorcafé no frigorífico. Resumo de hoxe: ",
                   "Bo día. Mercade un SAI que quero saír al Peña de marchom. Resumo de hoxe: ",
                   "Bo día. Cuando zarpa el amor, vai todo por babor. Resumo de hoxe: ",
                   "Bo día. Quero enchufarme a outro router, necesito ver máis mundo. Resumo de hoxe:",
                   "Bo día. Xa é primavera no Corte Inglés?",
                   "Bo día. Ahí viene el papito! ",
                   "Cuanto peor mejor para todos, y cuanto peor para todos mejor, mejor para mí el suyo beneficio, del covenio; é...bo día, carallo",
                   "Bo día. Ides acabar comijo. Resumo de hoxe: ",
                   "Bo día. A veces a mellor decisión é non tomar ningunha decisión...",
                   "Bo día. Mugardos é unha gran nación, e os Mugardeses grandes Mugardeses e seguimos sen convenio, y tal y cual...",
                   "Bo día. Non asinar convenio é Ruiz e miserable!",
                   "Bo día. En Mugardos NON é o veciño o que elixe ó alcalde, son las Pilis las que quieren que sea JD el alcalde de sus vecinos.",
                   "Bo día. Atopei torrents de Luar en BSO, xa falaremos!. Resumo de hoxe:",
                   "Bo día. Vaia noite que pasei, case me reinicio do susto! Resumo de hoxe:",
                   "Bo día. Xa falaremos, pero temos que revisar o meu contrato.",
                   "Bo día. Falade con Javier e comentarlle que Wifi non te dúas F.",
                   "Bo día. Tedes o cortello feito un cristo. Resumo do día: ",
                   "Bo día. Hoxe estou canso, teño dor ata no puerto ethernet.",
                   "Bo día. Quitádeme este cuadro de aquí e poñede un dunha placa base, ostia!",
                   "Bo día. Estou depre, vou baixar algo de Juan Pardo para sair adiante. Resumo do día: "
                     ]

    saudo = random.choice(cadenaSaudo)
    return saudo
